dataset: CGQA
first_split_size: 30
other_split_size: 10
schedule:
- 30
schedule_type: cosine
batch_size: 32
optimizer: Adam
lr: 0.0001
momentum: 0.9
weight_decay: 0
model_type: zoo_decoder
model_name: vit_decoder_imnet
max_task: -1
#dataroot: data
workers: 4
validation: False
train_aug: True
rand_split: True