dataset: CGQA
first_split_size: 50
other_split_size: 5
schedule:
- [[50], [0], [50]]   # 实际跑需要大一些 epoch
- [[50], [0], [50]]   # T * [[epochs for slots], [enhance reuse], [learn new prompt]]
schedule_type: cosine
slot_schedule_type: cosine
#batch_size: 32
optimizer: Adam
#lr:
#- 0.0005
#- 0.0005
momentum: 0.9
weight_decay: 0
model_type: zoo
model_name: vit_pt_imnet
#max_task: -1     # -1 for all
#dataroot: ../datasets
workers: 4
validation: False
train_aug: True
rand_split: True
logit_task_mask_top_k: 0